CREATE TABLE member (
                        id          NUMBER GENERATED BY DEFAULT AS IDENTITY,
                        email       NVARCHAR2(255) NOT NULL,
                        provider    NVARCHAR2(255) NOT NULL,
                        nickname    NVARCHAR2(255) NOT NULL,
                        PRIMARY KEY (id)
);

create table post
(
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY,
    tag           NVARCHAR2(255),
    title         NVARCHAR2(255),
    content       NVARCHAR2(255),
    create_date   TIMESTAMP,
    modified_date TIMESTAMP,
    views         NUMBER,
    writer_id     NUMBER,
    PRIMARY KEY (id),
    FOREIGN KEY (writer_id) REFERENCES member (id) ON DELETE CASCADE
);

create table reply
(
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY,
    message       NVARCHAR2(255),
    create_date   TIMESTAMP,
    modified_date TIMESTAMP,
    post_id       NUMBER,
    writer_id     NUMBER,
    topic_id      NUMBER,
    PRIMARY KEY (id),
    FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE SET NULL,
    FOREIGN KEY (writer_id) REFERENCES member (id) ON DELETE CASCADE,
    FOREIGN KEY (topic_id) REFERENCES reply (id) ON DELETE SET NULL
);

create table upload
(
    id       NUMBER GENERATED BY DEFAULT AS IDENTITY,
    filename NVARCHAR2(255),
    uuid     NVARCHAR2(255),
    post_id  NUMBER,
    uploader_id NUMBER,
    primary key (id),
    FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE,
    FOREIGN KEY (uploader_id) REFERENCES member (id) ON DELETE CASCADE
);
